### ISSUE TITLE
Doesn't work on Linux Mint

### ISSUE THREAD

**Issue by bontchev** [taviso/ctypes.sh#36] opened 2016-07-18 18:51 UTC
I couldn't get it to work on Linux Mint. Probably because it is not properly installed; the installation instructions need work.

Some of it is not your fault. It is specified that it depends on libffi - and installing that "out of the box" didn't work, either, producing some bizarre errors about missing macros. I figured out that compiling libffi depends on two things that were not installed by default on my machine:

- libtool
- makeinfo (in order to install that one, you actually have to install "texinfo")

After installing them, libffi compiled and installed. After running autogen.sh, configure and make, the things compiles, albeit with a lot of warnings. Most of them are about ignoring the return value of asprintf(), but there are others:

types.c:51:13: warning: format '%lu' expects argument of type 'long unsigned int', but argument 2 has type 'size_t' [-Wformat=]
             builtin_error("cannot handle size %lu", type->size);

types.c:79:9: warning: passing argument 2 of 'check_parse_long' from incompatible pointer type [enabled by default]
         if (check_parse_long(parameter, &n)) {

util.h:4:6: note: expected 'long int *' but argument is of type 'intmax_t *'
 bool check_parse_long(const char *number, long *result);

unpack.c:83:25: warning: format '%lu' expects argument of type 'long unsigned int', but argument 4 has type 'arrayind_t' [-Wformat=]
                         element->ind);

unpack.c:237:25: warning: format '%lu' expects argument of type 'long unsigned int', but argument 4 has type 'arrayind_t' [-Wformat=]
                         element->ind);

The installed program simply doesn't work - trying the various examples in the test directory results in segmentation faults and other errors.

**Comment by taviso** [comment] 2016-07-18 19:01
Those warnings are harmless, it's safe to ignore them.

I'm not familiar with Linux Mint, but I think the issue here is that `./configure` is detecting that not all dependencies are available and disabling some features that the testcases use.

You probably just need to do something like this:

`apt-get install libffi-dev libdw-dev libelf-dev`, and then run `./configure` again, make sure it doesn't say "AUTOMATIC STRUCT SUPPORT IS DISABLED" at the end.

**Comment by cemeyer** [comment] 2016-07-18 19:48
Some of those warnings are harmless on amd64, but not on e.g. i386 or other 32-bit platforms.  The first is probably not a problem as long as size_t matches long on your platform (seems very likely), but is also easy to fix — replace `%lu` with `%zu`.

The second is a problem on platforms with 32-bit `long`.  Usually `intmax_t` is 64-bit on those platforms.  So either pass in a `long` to `check_parse_long()` or change `check_parse_long()` to emit an `intmax_t` (probably requires changing other callers, though?).

I don't know what `arrayind_t` is, but assuming it's `size_t`, again, just change `%lu` to `%zu`.

As far as the seg faults, can you paste backtrace(s) or try installing libffi-dev, libtool, texinfo, etc and trying again?  Cheers.

**Comment by bontchev** [comment] 2016-07-18 20:07
> Those warnings are harmless, it's safe to ignore them.

When I was studying programming (a lifetime ago), I was told that a good programmer should strive to reduce the number of compiler warnings to zero otherwise some of them will bite him in the ass sooner or later. The compiler outputs them for a reason and not polishing the code to avoid them is just a sign of sloppyness.

> apt-get install libffi-dev libdw-dev libelf-dev

Well, mentioning this in the installation instructions might be a good idea. Same for libffi-dev. (I tried installing "libffi" but there was no such thing in the repository, so I had to rebuild it from GitHub.)

> run ./configure again, make sure it doesn't say "AUTOMATIC STRUCT SUPPORT IS DISABLED" at the end

It does not. I can't see any complaints about missing stuff any more, either. I rebuilt the program (make clean; make; sudo make install) and now some of the tests work - but not all.

In particular, these fail:

- math.sh - where is libm.so supposed to be located? Maybe it can't be found for some reason?

- stat.sh - it prints

/etc/passwd
	uid:  0
	gid:  0
	mode: 0
	size: 0
FAIL

- structs.sh - it prints

Testing nested anonymous and named structs...
PASS
Testing unions work, and selecting union members...
PASS 1/2
PASS 2/2
Testing structs with many different types...
FAIL

- wget.sh - I figured our where the bug in it is and opened a separate issue about it.

**Comment by bontchev** [comment] 2016-07-18 20:19
structs.sh exits after the first fail. I commented out the exits, so that I can see which tests pass and which fail. Here is the result:

Testing nested anonymous and named structs...
PASS
Testing unions work, and selecting union members...
PASS 1/2
PASS 2/2
Testing structs with many different types...
FAIL
Testing structs with arrays...
PASS
Testing structs with embedded enums...
FAIL
Check that anonymous structures referenced via typedef work...
PASS
Check that structs with funky packing work...
PASS
Testing structs that dont work yet, but shouldnt crash (errors are normal)...
./structs.sh: line 136: struct: multi-dimensional arrays are not currently supported
./structs.sh: line 136: struct: warning: complexarray could not be found; check `help struct` for more
./structs.sh: line 137: struct: unions of complex types (e.g. structures) are not currently supported
./structs.sh: line 137: struct: warning: complexunion could not be found; check `help struct` for more
PASS

**Comment by taviso** [comment] 2016-07-18 20:28
Hopefully distributions will eventually package the library and installation will be a breeze - but until then we have to assume some familiarity with debugging autotool builds - there are too many possible distributions that we can list detailed instructions for them all.

Silencing compiler warnings is a noble goal, but it is entirely unrelated to any problems here.

> math.sh - where is libm.so supposed to be located? Maybe it can't be found for some reason?

If libm is not in your standard library search path, then you would have big problems - so that's probably not the issue here.

On some systems libm.so is a linker script, and the real library is libm.so.6 but that is supported, and I have never seen any other configuration. What is the output?

> structs.sh exits after the first fail. I commented out the exits, so that I can see which tests pass and which fail. Here is the result:

Could you get the output of `bash -x structs.sh` that will better explain what happened...

**Comment by bontchev** [comment] 2016-07-19 08:55
Here are the traces from mash.sh and structs.sh. Apparently, math.sh fails due to a localization issue? (Again, the whole world is not the USA, you know.) I can't figure out why structs.sh fails - something to do with the default int/long size, perhaps? This is a 32-bit Linux.

mash.sh:

+ source ctypes.sh
++ initialize_ctypes_module
++ local prefix=/usr/local
++ local exec_prefix=/usr/local
++ builtins=(callback dlcall dlclose dlopen dlsym pack unpack struct sizeof)
++ local -a builtins
++ enable -f ctypes.so callback dlcall dlclose dlopen dlsym pack unpack struct sizeof
++ enable -f /usr/local/lib/ctypes.so callback dlcall dlclose dlopen dlsym pack unpack struct sizeof
++ unset initialize_ctypes_module
++ declare -r NULL=pointer:0
++ declare -r STDIN_FILENO=int:0
++ declare -r STDOUT_FILENO=int:1
++ declare -r STDERR_FILENO=int:2
+ set -e
+ dlopen libm.so
+ verify_result sin double:0 double 0.000000
+ dlcall -n result -r double sin double:0
+ test double:0,000000 '!=' double:0.000000
+ echo FAIL
FAIL
+ exit 1

structs.sh:

+ source ctypes.sh
++ initialize_ctypes_module
++ local prefix=/usr/local
++ local exec_prefix=/usr/local
++ builtins=(callback dlcall dlclose dlopen dlsym pack unpack struct sizeof)
++ local -a builtins
++ enable -f ctypes.so callback dlcall dlclose dlopen dlsym pack unpack struct sizeof
++ enable -f /usr/local/lib/ctypes.so callback dlcall dlclose dlopen dlsym pack unpack struct sizeof
++ unset initialize_ctypes_module
++ declare -r NULL=pointer:0
++ declare -r STDIN_FILENO=int:0
++ declare -r STDOUT_FILENO=int:1
++ declare -r STDERR_FILENO=int:2
+ set -e
+ dlopen ./structs.so
+ echo 'Testing nested anonymous and named structs...'
Testing nested anonymous and named structs...
+ struct nested nested
++ sizeof nested
+ compare_gdb_size nested 16
+ gdb -q -ex 'file structs.so' -ex 'q sizeof(nested) != 16' -ex 'q 0'
+ test int '!=' int
+ test int '!=' int
+ test int '!=' int
+ test int '!=' int
+ echo PASS
PASS
+ echo 'Testing unions work, and selecting union members...'
Testing unions work, and selecting union members...
+ struct hasunion hasunion
++ sizeof hasunion
+ compare_gdb_size hasunion 16
+ gdb -q -ex 'file structs.so' -ex 'q sizeof(hasunion) != 16' -ex 'q 0'
+ test int '!=' int
+ test uchar '!=' uchar
+ test -z ''
+ test -z ''
+ test uchar '!=' uchar
+ echo PASS 1/2
PASS 1/2
+ struct -u g:f,:i hasunion hasunion
+ test double '!=' double
+ test ushort '!=' ushort
+ test -z ''
+ test -z ''
+ echo PASS 2/2
PASS 2/2
+ echo 'Testing structs with many different types...'
Testing structs with many different types...
+ struct manytypes manytypes
++ sizeof manytypes
+ compare_gdb_size manytypes 36
+ gdb -q -ex 'file structs.so' -ex 'q sizeof(manytypes) != 36' -ex 'q 0'
+ test uchar '!=' uchar
+ test ushort '!=' ushort
+ test unsigned '!=' unsigned
+ test uint64 '!=' ulong
+ echo FAIL
FAIL
+ echo 'Testing structs with arrays...'
Testing structs with arrays...
+ struct hasarray hasarray
++ sizeof hasarray
+ compare_gdb_size hasarray 128
+ gdb -q -ex 'file structs.so' -ex 'q sizeof(hasarray) != 128' -ex 'q 0'
+ test int '!=' int
+ test int '!=' int
+ test -z ''
+ test -z ''
+ echo PASS
PASS
+ echo 'Testing structs with embedded enums...'
Testing structs with embedded enums...
+ struct hasenum hasenum
++ sizeof hasenum
+ compare_gdb_size hasenum 8
+ gdb -q -ex 'file structs.so' -ex 'q sizeof(hasenum) != 8' -ex 'q 0'
+ test int '!=' int
+ test int '!=' long
+ echo FAIL
FAIL
+ struct -a unnamed_t unnamed
+ echo 'Check that anonymous structures referenced via typedef work...'
Check that anonymous structures referenced via typedef work...
++ sizeof -a unnamed_t
+ compare_gdb_size unnamed_t 8
+ gdb -q -ex 'file structs.so' -ex 'q sizeof(unnamed_t) != 8' -ex 'q 0'
+ test int '!=' int
+ test long '!=' long
+ echo PASS
PASS
+ echo 'Check that structs with funky packing work...'
Check that structs with funky packing work...
+ struct mixedpack mixedpack
++ sizeof mixedpack
+ compare_gdb_size mixedpack 16
+ gdb -q -ex 'file structs.so' -ex 'q sizeof(mixedpack) != 16' -ex 'q 0'
+ test uchar '!=' uchar
+ test unsigned '!=' unsigned
+ test uchar '!=' uchar
+ test unsigned '!=' unsigned
+ echo PASS
PASS
+ echo 'Testing structs that dont work yet, but shouldnt crash (errors are normal)...'
Testing structs that dont work yet, but shouldnt crash (errors are normal)...
+ struct complexarray complexarray
structs.sh: line 136: struct: multi-dimensional arrays are not currently supported
structs.sh: line 136: struct: warning: complexarray could not be found; check `help struct` for more
+ true
+ struct complexunion complexunion
structs.sh: line 137: struct: unions of complex types (e.g. structures) are not currently supported
structs.sh: line 137: struct: warning: complexunion could not be found; check `help struct` for more
+ true
+ struct bitfields bitfields
+ echo PASS
PASS
+ exit 0

**Comment by taviso** [comment] 2016-07-19 14:07
Thanks for the debugging output - but I'm not sure what the correct fix is here, my ignorance of localization means I have more questions.  When you're writing C, Java or whatever - would you normally write `3,141` instead of `3.141` when writing floats?

I /think/ we need to disable localization, but maybe I don't know what I'm talking about.

The `structs.sh` error does indeed look like some 32bit problem, that is simple to solve. Luckily it seems like everything is basically working, the test cases just need some improvement.

**Comment by bontchev** [comment] 2016-07-19 14:29
Yes, disabling the localization within the math.sh script fixes the problem. Just put a line

`LC_ALL=C`

at the beginning. I don't know how to solve the problems in structs.sh and stat.sh, though. Oh, wait, I forgot the stat.sh trace. Here it is:
```

+ source ctypes.sh
++ initialize_ctypes_module
++ local prefix=/usr/local
++ local exec_prefix=/usr/local
++ builtins=(callback dlcall dlclose dlopen dlsym pack unpack struct sizeof)
++ local -a builtins
++ enable -f ctypes.so callback dlcall dlclose dlopen dlsym pack unpack struct sizeof
++ enable -f /usr/local/lib/ctypes.so callback dlcall dlclose dlopen dlsym pack unpack struct sizeof
++ unset initialize_ctypes_module
++ declare -r NULL=pointer:0
++ declare -r STDIN_FILENO=int:0
++ declare -r STDOUT_FILENO=int:1
++ declare -r STDERR_FILENO=int:2
+ set -e
+ struct -m statbuf stat passwd
++ uname
+ test Linux == Linux
+ dlcall -r int __xstat 0 /etc/passwd pointer:0x8224d08
+ unpack pointer:0x8224d08 passwd
+ printf '/etc/passwd\n'
/etc/passwd
+ printf '\tuid:  %u\n' 0
	uid:  0
+ printf '\tgid:  %u\n' 0
	gid:  0
+ printf '\tmode: %o\n' 0
	mode: 0
+ printf '\tsize: %u\n' 0
	size: 0
+ dlcall free pointer:0x8224d08
++ wc -c
+ test 0 -eq 1939
+ echo FAIL
FAIL
+ exit 1

```

**Comment by taviso** [comment] 2016-07-19 14:53
Yes, that xstat call is 64bit specific - I think just changing it to `__xstat 3` instead of `__xstat 0` would work.

OK, so I think we should close this issue because installation is working as intended, and open these:

1. Most importantly, figure out how to handle localization. Are roundtrips between scanf and printf always guaranteed to work? If so, then we just have to make sure scripts declare localization if they hardcode something. If not, then we need to disable it somewhere.
2. Minor issue, some of the testcases assume 64bit.
3. Should probably not have a testcase that uses sockets, but for 1.2 I'll probably try to integrate with autoconf tests anyway so `make check` works.

**Comment by cemeyer** [comment] 2016-07-19 15:10
For test values, set the locale to C as Vesselin suggests.  I don't know if scanf and printf are guaranteed to round trip in all locales (and even if so, if they do so correctly on all platforms…).

**Comment by taviso** [comment] 2016-07-19 15:38
OK, sounds ok to me.

**Comment by taviso** [comment] 2016-07-19 15:51
Done - fix committed to head. I'll close this for now and make sure tests support 32bit when the tests are ported to autoconf.

Luckily this seems to just be incomplete tests and examples, the code looks like it's working correctly here!

Thanks so much for testing @bontchev!

**Closed by taviso** 2016-07-19 15:51 UTC

**Comment by bontchev** [comment] 2016-07-19 17:59
> Most importantly, figure out how to handle localization. Are roundtrips between scanf and printf always guaranteed to work? If so, then we just have to make sure scripts declare localization if they hardcode something. If not, then we need to disable it somewhere.

It's a rare and complicated issue. For instance,

`printf("%1.2f\n", 3.14);`

displays `3.14` regardless of the locale. The locale mostly impacts the shell (and maybe some higher-level outputs - GTK, perhaps?) - but `bash` can't do floating point, so it's normally not a problem there. `ksh` can do floating point and the suggested solution there is precisely to disable the localization via `LC_ALL=C`, if you are going to use hard-coded floating point constants in expressions:

https://unix.stackexchange.com/questions/87745/what-does-lc-all-c-do

Thanks for fixing it and please don't forget to update the prerequisites/install instructions.

**Comment by taviso** [comment] 2016-07-19 18:15
Bash doesn't support floating point, but ctypes.sh does via our type-marshaling system. But I just tested all locales via `for i in $(locale -a)`, and it looks like round-trips do seem to work - so the only issue is if we use hardcoded values in scripts, where LC_ALL=C will do.

If that turns out to not be reliable somewhere, we will need something like `push(locale, "C"); xxx; poplocale()` in ctypes routines.  I think it's looking okay though.

**Comment by taviso** [comment] 2016-07-19 18:44
Regarding the installation instructions - I /think/ I'm happy with how they are, but maybe you can give me an example of how you think it can be improved?

The prerequisites are already clearly listed on the front page of the project, and in the README - I'm not sure what else we can do here. I could add more verbose output to autoconf, but I think we're approximately aligned with what other projects are doing...

We *could* give detailed instructions on installing packages, but I'd rather leave that up to the distributions, duplicating them here seems like a never ending task.

**Comment by bontchev** [comment] 2016-07-19 22:10
If you want to be very surgical about it, instead of disabling the whole locale, you could probably just set

`LC_NUMERIC=en_US.UTF-8`

i.e., set the value of the decimal point to whatever the US locale uses (a dot).

Regarding the installation, I had to install many things that weren't obvious from the instructions. `libffi-dev` instead of `libffi`, for sure. `libdw-dev`, too; it wasn't present on my system and it wouldn't work without it. Maybe `libtool` and `texutil`? I needed to install them, in order to run `autogen.sh` and `configure` and compile the `libffi` from its GitHub repository - but they will probably be needed for the corresponding configuration scripts of this project, too? `libc6-dbg`, maybe? Although I think it was already up-to-date on my system... The instructions say that `libelf` and `elfutils` are optional, but `configure` was complaining that they were missing.

**Comment by taviso** [comment] 2016-07-19 23:09
You need libtool to build from git HEAD (mostly intended for developers), but not for the stable release build?

The way that distribution name and organize packages varies, for example libffi-dev is needed on debian, but libffi-devel is needed on RedHat. On Debian you need libdw-dev, but elfutils-devel on RedHat and it's completely different again on FreeBSD.

So i think we don't want to have distribution specific instructions, and instead allow distributions to document how to translate "libffi" into a package name. To give you an example of how complicated this gets, on RedHat you would do `yum search libffi`, on debian `apt-cache search libffi`, Fedora `dnf search libffi`...and so on. I think it's best to let distributions have generic instructions here...because I have no idea what you do on SuSE or arch or NetBSD.

libelf and elfutils really are optional, that's not a bug, and when libc6-dbg (that's called glibc-debuginfo on redhat!) is missing, it says "type help struct for more information" which does explain what to do.
